# Generated by Django 3.2.5 on 2023-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_usercourses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
