# Generated by Django 3.2.5 on 2023-11-17 04:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
